### ISSUE TITLE
Please do not create so many entries in the nodes list menu

### ISSUE THREAD

**Issue by deepfree2023** [dagthomas/comfyui_dagthomas#15]
The nodes are quite useful,  but the style nodes appear in the top layer of nodes menu, and one style one position, that's very annoying.  Hope a better solution for that.

**Comment by dagthomas** [comment]
Think I have fixed it in the newest release, thanks for your input!

**Comment by deepfree2023** [comment]
Hi, the problem still exists here:
![image](https://github.com/user-attachments/assets/9bf5d702-05ab-455a-bbb5-78059ad34a17)
![image](https://github.com/user-attachments/assets/ff6d7ebd-014f-4cbf-96d6-039a0dada84f)

**Comment by dagthomas** [comment]
Thank you for the screenshot, have pushed a fix now <3 Sorry for wasting your time!

**Comment by deepfree2023** [comment]
Problem solved, thanks for your work!
